// flow-typed signature: 893af3890bef92e37bbfeaffb3e492da
// flow-typed version: <<STUB>>/babel-preset-node6_v^11.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-node6'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-node6' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-node6/index' {
  declare module.exports: $Exports<'babel-preset-node6'>;
}
declare module 'babel-preset-node6/index.js' {
  declare module.exports: $Exports<'babel-preset-node6'>;
}
