// flow-typed signature: f693be044bad27bf62bb39d9f1fc003f
// flow-typed version: <<STUB>>/better-npm-run_v0.0.8/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'better-npm-run'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'better-npm-run' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'better-npm-run/lib/exec' {
  declare module.exports: any;
}

declare module 'better-npm-run/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'better-npm-run/index' {
  declare module.exports: $Exports<'better-npm-run'>;
}
declare module 'better-npm-run/index.js' {
  declare module.exports: $Exports<'better-npm-run'>;
}
declare module 'better-npm-run/lib/exec.js' {
  declare module.exports: $Exports<'better-npm-run/lib/exec'>;
}
declare module 'better-npm-run/test.js' {
  declare module.exports: $Exports<'better-npm-run/test'>;
}
