// flow-typed signature: 346a91db50abda9def7e7bdabf908c7d
// flow-typed version: <<STUB>>/bootstrap-sass-loader_v^1.0.9/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-sass-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-sass-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-sass-loader/bootstrap-sass-no-customizations.config' {
  declare module.exports: any;
}

declare module 'bootstrap-sass-loader/bootstrap-sass-scripts.loader' {
  declare module.exports: any;
}

declare module 'bootstrap-sass-loader/bootstrap-sass-styles.loader' {
  declare module.exports: any;
}

declare module 'bootstrap-sass-loader/bootstrap-sass.config' {
  declare module.exports: any;
}

declare module 'bootstrap-sass-loader/bootstrapSassPath' {
  declare module.exports: any;
}

declare module 'bootstrap-sass-loader/index.loader' {
  declare module.exports: any;
}

declare module 'bootstrap-sass-loader/logger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-sass-loader/bootstrap-sass-no-customizations.config.js' {
  declare module.exports: $Exports<'bootstrap-sass-loader/bootstrap-sass-no-customizations.config'>;
}
declare module 'bootstrap-sass-loader/bootstrap-sass-scripts.loader.js' {
  declare module.exports: $Exports<'bootstrap-sass-loader/bootstrap-sass-scripts.loader'>;
}
declare module 'bootstrap-sass-loader/bootstrap-sass-styles.loader.js' {
  declare module.exports: $Exports<'bootstrap-sass-loader/bootstrap-sass-styles.loader'>;
}
declare module 'bootstrap-sass-loader/bootstrap-sass.config.js' {
  declare module.exports: $Exports<'bootstrap-sass-loader/bootstrap-sass.config'>;
}
declare module 'bootstrap-sass-loader/bootstrapSassPath.js' {
  declare module.exports: $Exports<'bootstrap-sass-loader/bootstrapSassPath'>;
}
declare module 'bootstrap-sass-loader/index' {
  declare module.exports: $Exports<'bootstrap-sass-loader'>;
}
declare module 'bootstrap-sass-loader/index.js' {
  declare module.exports: $Exports<'bootstrap-sass-loader'>;
}
declare module 'bootstrap-sass-loader/index.loader.js' {
  declare module.exports: $Exports<'bootstrap-sass-loader/index.loader'>;
}
declare module 'bootstrap-sass-loader/logger.js' {
  declare module.exports: $Exports<'bootstrap-sass-loader/logger'>;
}
