// flow-typed signature: d220701e8b7b79773155a7ca50232548
// flow-typed version: <<STUB>>/browser-request_v^0.3.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-request/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-request/index' {
  declare module.exports: $Exports<'browser-request'>;
}
declare module 'browser-request/index.js' {
  declare module.exports: $Exports<'browser-request'>;
}
declare module 'browser-request/test.js' {
  declare module.exports: $Exports<'browser-request/test'>;
}
