// flow-typed signature: e43c0c1efdcee4c844918aff9b9b1e07
// flow-typed version: <<STUB>>/chai-subset_v^1.3.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-subset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-subset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-subset/lib/chai-subset' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-subset/lib/chai-subset.js' {
  declare module.exports: $Exports<'chai-subset/lib/chai-subset'>;
}
