// flow-typed signature: c3ce74d35d2c383f5a6636bd351d70f2
// flow-typed version: <<STUB>>/draft-js-ast-importer_v^0.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-ast-importer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-ast-importer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-ast-importer/lib/camelCase' {
  declare module.exports: any;
}

declare module 'draft-js-ast-importer/lib/compiler' {
  declare module.exports: any;
}

declare module 'draft-js-ast-importer/lib/dataSchema' {
  declare module.exports: any;
}

declare module 'draft-js-ast-importer/lib/flatten' {
  declare module.exports: any;
}

declare module 'draft-js-ast-importer/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-ast-importer/test/fixtures/content/ast' {
  declare module.exports: any;
}

declare module 'draft-js-ast-importer/test/fixtures/content/raw' {
  declare module.exports: any;
}

declare module 'draft-js-ast-importer/test/fixtures/depth/ast' {
  declare module.exports: any;
}

declare module 'draft-js-ast-importer/test/fixtures/depth/raw' {
  declare module.exports: any;
}

declare module 'draft-js-ast-importer/test/fixtures/remove-block-keys' {
  declare module.exports: any;
}

declare module 'draft-js-ast-importer/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-ast-importer/lib/camelCase.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/lib/camelCase'>;
}
declare module 'draft-js-ast-importer/lib/compiler.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/lib/compiler'>;
}
declare module 'draft-js-ast-importer/lib/dataSchema.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/lib/dataSchema'>;
}
declare module 'draft-js-ast-importer/lib/flatten.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/lib/flatten'>;
}
declare module 'draft-js-ast-importer/lib/index.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/lib/index'>;
}
declare module 'draft-js-ast-importer/test/fixtures/content/ast.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/test/fixtures/content/ast'>;
}
declare module 'draft-js-ast-importer/test/fixtures/content/raw.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/test/fixtures/content/raw'>;
}
declare module 'draft-js-ast-importer/test/fixtures/depth/ast.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/test/fixtures/depth/ast'>;
}
declare module 'draft-js-ast-importer/test/fixtures/depth/raw.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/test/fixtures/depth/raw'>;
}
declare module 'draft-js-ast-importer/test/fixtures/remove-block-keys.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/test/fixtures/remove-block-keys'>;
}
declare module 'draft-js-ast-importer/test/index.js' {
  declare module.exports: $Exports<'draft-js-ast-importer/test/index'>;
}
