// flow-typed signature: 8acccaf5ae57e988826fb9ef0cc74fff
// flow-typed version: <<STUB>>/draft-js-emoji-plugin_v^2.0.0-beta1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-emoji-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-emoji-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-emoji-plugin/lib/Emoji/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/emojiStrategy' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/EmojiSuggestions/Entry/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/EmojiSuggestions/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/EmojiSuggestionsPortal/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/emojiSuggestionsStrategy' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/modifiers/addEmoji' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/modifiers/attachImmutableEntitiesToEmojis' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/convertShortNameToUnicode' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/decodeOffsetKey' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/emojioneList' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/escapeMap' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/getSearchText' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/getWordAt' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/mappedUnicode' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/positionSuggestions' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/shortNames' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/unicodeRegex' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-emoji-plugin/lib/Emoji/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/Emoji/index'>;
}
declare module 'draft-js-emoji-plugin/lib/emojiStrategy.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/emojiStrategy'>;
}
declare module 'draft-js-emoji-plugin/lib/EmojiSuggestions/Entry/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/EmojiSuggestions/Entry/index'>;
}
declare module 'draft-js-emoji-plugin/lib/EmojiSuggestions/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/EmojiSuggestions/index'>;
}
declare module 'draft-js-emoji-plugin/lib/EmojiSuggestionsPortal/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/EmojiSuggestionsPortal/index'>;
}
declare module 'draft-js-emoji-plugin/lib/emojiSuggestionsStrategy.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/emojiSuggestionsStrategy'>;
}
declare module 'draft-js-emoji-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/index'>;
}
declare module 'draft-js-emoji-plugin/lib/modifiers/addEmoji.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/modifiers/addEmoji'>;
}
declare module 'draft-js-emoji-plugin/lib/modifiers/attachImmutableEntitiesToEmojis.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/modifiers/attachImmutableEntitiesToEmojis'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/convertShortNameToUnicode.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/convertShortNameToUnicode'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/decodeOffsetKey.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/decodeOffsetKey'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/emojioneList.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/emojioneList'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/escapeMap.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/escapeMap'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/getSearchText.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/getSearchText'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/getWordAt.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/getWordAt'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/mappedUnicode.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/mappedUnicode'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/positionSuggestions.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/positionSuggestions'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/shortNames.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/shortNames'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/unicodeRegex.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/unicodeRegex'>;
}
