// flow-typed signature: aa9e8f5c00bac75b35d93a80c3c86729
// flow-typed version: <<STUB>>/draft-js-ast-exporter_v^0.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-ast-exporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-ast-exporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-ast-exporter/lib/dataSchema' {
  declare module.exports: any;
}

declare module 'draft-js-ast-exporter/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-ast-exporter/lib/processor' {
  declare module.exports: any;
}

declare module 'draft-js-ast-exporter/test/fixtures/content-exported-entity' {
  declare module.exports: any;
}

declare module 'draft-js-ast-exporter/test/fixtures/content-exported' {
  declare module.exports: any;
}

declare module 'draft-js-ast-exporter/test/fixtures/content' {
  declare module.exports: any;
}

declare module 'draft-js-ast-exporter/test/fixtures/depth-exported' {
  declare module.exports: any;
}

declare module 'draft-js-ast-exporter/test/fixtures/depth' {
  declare module.exports: any;
}

declare module 'draft-js-ast-exporter/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-ast-exporter/lib/dataSchema.js' {
  declare module.exports: $Exports<'draft-js-ast-exporter/lib/dataSchema'>;
}
declare module 'draft-js-ast-exporter/lib/index.js' {
  declare module.exports: $Exports<'draft-js-ast-exporter/lib/index'>;
}
declare module 'draft-js-ast-exporter/lib/processor.js' {
  declare module.exports: $Exports<'draft-js-ast-exporter/lib/processor'>;
}
declare module 'draft-js-ast-exporter/test/fixtures/content-exported-entity.js' {
  declare module.exports: $Exports<'draft-js-ast-exporter/test/fixtures/content-exported-entity'>;
}
declare module 'draft-js-ast-exporter/test/fixtures/content-exported.js' {
  declare module.exports: $Exports<'draft-js-ast-exporter/test/fixtures/content-exported'>;
}
declare module 'draft-js-ast-exporter/test/fixtures/content.js' {
  declare module.exports: $Exports<'draft-js-ast-exporter/test/fixtures/content'>;
}
declare module 'draft-js-ast-exporter/test/fixtures/depth-exported.js' {
  declare module.exports: $Exports<'draft-js-ast-exporter/test/fixtures/depth-exported'>;
}
declare module 'draft-js-ast-exporter/test/fixtures/depth.js' {
  declare module.exports: $Exports<'draft-js-ast-exporter/test/fixtures/depth'>;
}
declare module 'draft-js-ast-exporter/test/index.js' {
  declare module.exports: $Exports<'draft-js-ast-exporter/test/index'>;
}
