// flow-typed signature: 26037a50ab8c46aee18a19c96051b703
// flow-typed version: <<STUB>>/draft-js-hashtag-plugin_v^2.0.0-beta1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-hashtag-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-hashtag-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-hashtag-plugin/lib/Hashtag/index' {
  declare module.exports: any;
}

declare module 'draft-js-hashtag-plugin/lib/hashtagStrategy' {
  declare module.exports: any;
}

declare module 'draft-js-hashtag-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-hashtag-plugin/lib/utils/hashtagRegex' {
  declare module.exports: any;
}

declare module 'draft-js-hashtag-plugin/lib/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-hashtag-plugin/lib/Hashtag/index.js' {
  declare module.exports: $Exports<'draft-js-hashtag-plugin/lib/Hashtag/index'>;
}
declare module 'draft-js-hashtag-plugin/lib/hashtagStrategy.js' {
  declare module.exports: $Exports<'draft-js-hashtag-plugin/lib/hashtagStrategy'>;
}
declare module 'draft-js-hashtag-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-hashtag-plugin/lib/index'>;
}
declare module 'draft-js-hashtag-plugin/lib/utils/hashtagRegex.js' {
  declare module.exports: $Exports<'draft-js-hashtag-plugin/lib/utils/hashtagRegex'>;
}
declare module 'draft-js-hashtag-plugin/lib/utils/index.js' {
  declare module.exports: $Exports<'draft-js-hashtag-plugin/lib/utils/index'>;
}
