// flow-typed signature: d759923517afaf932304a64297f4fe7f
// flow-typed version: <<STUB>>/draft-js-mention-plugin_v^2.0.0-beta1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-mention-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-mention-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-mention-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/Mention/index' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/mentionStrategy' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/MentionSuggestions/Entry/Avatar/index' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/MentionSuggestions/Entry/index' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/MentionSuggestions/index' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/MentionSuggestionsPortal/index' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/mentionSuggestionsStrategy' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/modifiers/addMention' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/utils/decodeOffsetKey' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/utils/defaultSuggestionsFilter' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/utils/getSearchText' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/utils/getWordAt' {
  declare module.exports: any;
}

declare module 'draft-js-mention-plugin/lib/utils/positionSuggestions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-mention-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/index'>;
}
declare module 'draft-js-mention-plugin/lib/Mention/index.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/Mention/index'>;
}
declare module 'draft-js-mention-plugin/lib/mentionStrategy.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/mentionStrategy'>;
}
declare module 'draft-js-mention-plugin/lib/MentionSuggestions/Entry/Avatar/index.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/MentionSuggestions/Entry/Avatar/index'>;
}
declare module 'draft-js-mention-plugin/lib/MentionSuggestions/Entry/index.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/MentionSuggestions/Entry/index'>;
}
declare module 'draft-js-mention-plugin/lib/MentionSuggestions/index.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/MentionSuggestions/index'>;
}
declare module 'draft-js-mention-plugin/lib/MentionSuggestionsPortal/index.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/MentionSuggestionsPortal/index'>;
}
declare module 'draft-js-mention-plugin/lib/mentionSuggestionsStrategy.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/mentionSuggestionsStrategy'>;
}
declare module 'draft-js-mention-plugin/lib/modifiers/addMention.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/modifiers/addMention'>;
}
declare module 'draft-js-mention-plugin/lib/utils/decodeOffsetKey.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/utils/decodeOffsetKey'>;
}
declare module 'draft-js-mention-plugin/lib/utils/defaultSuggestionsFilter.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/utils/defaultSuggestionsFilter'>;
}
declare module 'draft-js-mention-plugin/lib/utils/getSearchText.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/utils/getSearchText'>;
}
declare module 'draft-js-mention-plugin/lib/utils/getWordAt.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/utils/getWordAt'>;
}
declare module 'draft-js-mention-plugin/lib/utils/positionSuggestions.js' {
  declare module.exports: $Exports<'draft-js-mention-plugin/lib/utils/positionSuggestions'>;
}
