// flow-typed signature: 551135d48125b0287d656a5fe037349b
// flow-typed version: <<STUB>>/envalid_v^2.4.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'envalid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'envalid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'envalid/example/env' {
  declare module.exports: any;
}

declare module 'envalid/example/server' {
  declare module.exports: any;
}

declare module 'envalid/lib/reporter' {
  declare module.exports: any;
}

declare module 'envalid/lib/validators' {
  declare module.exports: any;
}

declare module 'envalid/tests/test_basics' {
  declare module.exports: any;
}

declare module 'envalid/tests/test_dotenv' {
  declare module.exports: any;
}

declare module 'envalid/tests/test_reporter' {
  declare module.exports: any;
}

declare module 'envalid/tests/test_types' {
  declare module.exports: any;
}

declare module 'envalid/tests/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'envalid/example/env.js' {
  declare module.exports: $Exports<'envalid/example/env'>;
}
declare module 'envalid/example/server.js' {
  declare module.exports: $Exports<'envalid/example/server'>;
}
declare module 'envalid/index' {
  declare module.exports: $Exports<'envalid'>;
}
declare module 'envalid/index.js' {
  declare module.exports: $Exports<'envalid'>;
}
declare module 'envalid/lib/reporter.js' {
  declare module.exports: $Exports<'envalid/lib/reporter'>;
}
declare module 'envalid/lib/validators.js' {
  declare module.exports: $Exports<'envalid/lib/validators'>;
}
declare module 'envalid/tests/test_basics.js' {
  declare module.exports: $Exports<'envalid/tests/test_basics'>;
}
declare module 'envalid/tests/test_dotenv.js' {
  declare module.exports: $Exports<'envalid/tests/test_dotenv'>;
}
declare module 'envalid/tests/test_reporter.js' {
  declare module.exports: $Exports<'envalid/tests/test_reporter'>;
}
declare module 'envalid/tests/test_types.js' {
  declare module.exports: $Exports<'envalid/tests/test_types'>;
}
declare module 'envalid/tests/utils.js' {
  declare module.exports: $Exports<'envalid/tests/utils'>;
}
