// flow-typed signature: 460ff12aeae526688f295e8e6b39143f
// flow-typed version: <<STUB>>/esformatter-jsx_v^7.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esformatter-jsx/lib/default-unformatted' {
  declare module.exports: any;
}

declare module 'esformatter-jsx/lib/falafel-helper' {
  declare module.exports: any;
}

declare module 'esformatter-jsx/lib/find-parent' {
  declare module.exports: any;
}

declare module 'esformatter-jsx/lib/format-jsx' {
  declare module.exports: any;
}

declare module 'esformatter-jsx/lib/iterate-reverse' {
  declare module.exports: any;
}

declare module 'esformatter-jsx/lib/parser-options' {
  declare module.exports: any;
}

declare module 'esformatter-jsx/lib/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esformatter-jsx/index' {
  declare module.exports: $Exports<'esformatter-jsx'>;
}
declare module 'esformatter-jsx/index.js' {
  declare module.exports: $Exports<'esformatter-jsx'>;
}
declare module 'esformatter-jsx/lib/default-unformatted.js' {
  declare module.exports: $Exports<'esformatter-jsx/lib/default-unformatted'>;
}
declare module 'esformatter-jsx/lib/falafel-helper.js' {
  declare module.exports: $Exports<'esformatter-jsx/lib/falafel-helper'>;
}
declare module 'esformatter-jsx/lib/find-parent.js' {
  declare module.exports: $Exports<'esformatter-jsx/lib/find-parent'>;
}
declare module 'esformatter-jsx/lib/format-jsx.js' {
  declare module.exports: $Exports<'esformatter-jsx/lib/format-jsx'>;
}
declare module 'esformatter-jsx/lib/iterate-reverse.js' {
  declare module.exports: $Exports<'esformatter-jsx/lib/iterate-reverse'>;
}
declare module 'esformatter-jsx/lib/parser-options.js' {
  declare module.exports: $Exports<'esformatter-jsx/lib/parser-options'>;
}
declare module 'esformatter-jsx/lib/plugin.js' {
  declare module.exports: $Exports<'esformatter-jsx/lib/plugin'>;
}
