// flow-typed signature: 07448895d37cbaa1afd04eac012fd31a
// flow-typed version: <<STUB>>/eslint-import-resolver-babel-module-alias_v^1.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-babel-module-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-babel-module-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-babel-module-alias/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-babel-module-alias/src/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-babel-module-alias/src/index'>;
}
