// flow-typed signature: 6bac428173ec5173f4c60b31c4ab124a
// flow-typed version: <<STUB>>/express-promise_v^0.4.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-promise/examples/mongoose/app' {
  declare module.exports: any;
}

declare module 'express-promise/examples/mongoose/routes/index' {
  declare module.exports: any;
}

declare module 'express-promise/examples/sequelize/app' {
  declare module.exports: any;
}

declare module 'express-promise/examples/sequelize/routes/index' {
  declare module.exports: any;
}

declare module 'express-promise/lib/express_promise' {
  declare module.exports: any;
}

declare module 'express-promise/test/basic' {
  declare module.exports: any;
}

declare module 'express-promise/test/json' {
  declare module.exports: any;
}

declare module 'express-promise/test/recursive' {
  declare module.exports: any;
}

declare module 'express-promise/test/render' {
  declare module.exports: any;
}

declare module 'express-promise/test/send' {
  declare module.exports: any;
}

declare module 'express-promise/test/skip_rule' {
  declare module.exports: any;
}

declare module 'express-promise/test/spec_helper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-promise/examples/mongoose/app.js' {
  declare module.exports: $Exports<'express-promise/examples/mongoose/app'>;
}
declare module 'express-promise/examples/mongoose/routes/index.js' {
  declare module.exports: $Exports<'express-promise/examples/mongoose/routes/index'>;
}
declare module 'express-promise/examples/sequelize/app.js' {
  declare module.exports: $Exports<'express-promise/examples/sequelize/app'>;
}
declare module 'express-promise/examples/sequelize/routes/index.js' {
  declare module.exports: $Exports<'express-promise/examples/sequelize/routes/index'>;
}
declare module 'express-promise/index' {
  declare module.exports: $Exports<'express-promise'>;
}
declare module 'express-promise/index.js' {
  declare module.exports: $Exports<'express-promise'>;
}
declare module 'express-promise/lib/express_promise.js' {
  declare module.exports: $Exports<'express-promise/lib/express_promise'>;
}
declare module 'express-promise/test/basic.js' {
  declare module.exports: $Exports<'express-promise/test/basic'>;
}
declare module 'express-promise/test/json.js' {
  declare module.exports: $Exports<'express-promise/test/json'>;
}
declare module 'express-promise/test/recursive.js' {
  declare module.exports: $Exports<'express-promise/test/recursive'>;
}
declare module 'express-promise/test/render.js' {
  declare module.exports: $Exports<'express-promise/test/render'>;
}
declare module 'express-promise/test/send.js' {
  declare module.exports: $Exports<'express-promise/test/send'>;
}
declare module 'express-promise/test/skip_rule.js' {
  declare module.exports: $Exports<'express-promise/test/skip_rule'>;
}
declare module 'express-promise/test/spec_helper.js' {
  declare module.exports: $Exports<'express-promise/test/spec_helper'>;
}
