// flow-typed signature: bcf39c671ca28d45f59f447f243c529e
// flow-typed version: <<STUB>>/express-status-monitor_v^0.1.5/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-status-monitor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-status-monitor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-status-monitor/examples/index' {
  declare module.exports: any;
}

declare module 'express-status-monitor/examples/tester' {
  declare module.exports: any;
}

declare module 'express-status-monitor/src/helpers/default-config' {
  declare module.exports: any;
}

declare module 'express-status-monitor/src/helpers/gather-os-metrics' {
  declare module.exports: any;
}

declare module 'express-status-monitor/src/helpers/on-headers-listener' {
  declare module.exports: any;
}

declare module 'express-status-monitor/src/helpers/send-metrics' {
  declare module.exports: any;
}

declare module 'express-status-monitor/src/helpers/socket-io-init' {
  declare module.exports: any;
}

declare module 'express-status-monitor/src/helpers/validate' {
  declare module.exports: any;
}

declare module 'express-status-monitor/src/middleware-wrapper' {
  declare module.exports: any;
}

declare module 'express-status-monitor/src/public/javascripts/app' {
  declare module.exports: any;
}

declare module 'express-status-monitor/test/helpers/gather-os-metrics.spec' {
  declare module.exports: any;
}

declare module 'express-status-monitor/test/helpers/on-headers-listener.spec' {
  declare module.exports: any;
}

declare module 'express-status-monitor/test/helpers/send-metrics.spec' {
  declare module.exports: any;
}

declare module 'express-status-monitor/test/helpers/socket-io-init.spec' {
  declare module.exports: any;
}

declare module 'express-status-monitor/test/helpers/validate.spec' {
  declare module.exports: any;
}

declare module 'express-status-monitor/test/middleware-wrapper.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-status-monitor/examples/index.js' {
  declare module.exports: $Exports<'express-status-monitor/examples/index'>;
}
declare module 'express-status-monitor/examples/tester.js' {
  declare module.exports: $Exports<'express-status-monitor/examples/tester'>;
}
declare module 'express-status-monitor/index' {
  declare module.exports: $Exports<'express-status-monitor'>;
}
declare module 'express-status-monitor/index.js' {
  declare module.exports: $Exports<'express-status-monitor'>;
}
declare module 'express-status-monitor/src/helpers/default-config.js' {
  declare module.exports: $Exports<'express-status-monitor/src/helpers/default-config'>;
}
declare module 'express-status-monitor/src/helpers/gather-os-metrics.js' {
  declare module.exports: $Exports<'express-status-monitor/src/helpers/gather-os-metrics'>;
}
declare module 'express-status-monitor/src/helpers/on-headers-listener.js' {
  declare module.exports: $Exports<'express-status-monitor/src/helpers/on-headers-listener'>;
}
declare module 'express-status-monitor/src/helpers/send-metrics.js' {
  declare module.exports: $Exports<'express-status-monitor/src/helpers/send-metrics'>;
}
declare module 'express-status-monitor/src/helpers/socket-io-init.js' {
  declare module.exports: $Exports<'express-status-monitor/src/helpers/socket-io-init'>;
}
declare module 'express-status-monitor/src/helpers/validate.js' {
  declare module.exports: $Exports<'express-status-monitor/src/helpers/validate'>;
}
declare module 'express-status-monitor/src/middleware-wrapper.js' {
  declare module.exports: $Exports<'express-status-monitor/src/middleware-wrapper'>;
}
declare module 'express-status-monitor/src/public/javascripts/app.js' {
  declare module.exports: $Exports<'express-status-monitor/src/public/javascripts/app'>;
}
declare module 'express-status-monitor/test/helpers/gather-os-metrics.spec.js' {
  declare module.exports: $Exports<'express-status-monitor/test/helpers/gather-os-metrics.spec'>;
}
declare module 'express-status-monitor/test/helpers/on-headers-listener.spec.js' {
  declare module.exports: $Exports<'express-status-monitor/test/helpers/on-headers-listener.spec'>;
}
declare module 'express-status-monitor/test/helpers/send-metrics.spec.js' {
  declare module.exports: $Exports<'express-status-monitor/test/helpers/send-metrics.spec'>;
}
declare module 'express-status-monitor/test/helpers/socket-io-init.spec.js' {
  declare module.exports: $Exports<'express-status-monitor/test/helpers/socket-io-init.spec'>;
}
declare module 'express-status-monitor/test/helpers/validate.spec.js' {
  declare module.exports: $Exports<'express-status-monitor/test/helpers/validate.spec'>;
}
declare module 'express-status-monitor/test/middleware-wrapper.spec.js' {
  declare module.exports: $Exports<'express-status-monitor/test/middleware-wrapper.spec'>;
}
