// flow-typed signature: 5682a8a453ac415702125cef05080cfb
// flow-typed version: <<STUB>>/font-awesome-webpack_v0.0.4/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'font-awesome-webpack/font-awesome-styles.loader' {
  declare module.exports: any;
}

declare module 'font-awesome-webpack/font-awesome.config' {
  declare module.exports: any;
}

declare module 'font-awesome-webpack/index.loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'font-awesome-webpack/font-awesome-styles.loader.js' {
  declare module.exports: $Exports<'font-awesome-webpack/font-awesome-styles.loader'>;
}
declare module 'font-awesome-webpack/font-awesome.config.js' {
  declare module.exports: $Exports<'font-awesome-webpack/font-awesome.config'>;
}
declare module 'font-awesome-webpack/index' {
  declare module.exports: $Exports<'font-awesome-webpack'>;
}
declare module 'font-awesome-webpack/index.js' {
  declare module.exports: $Exports<'font-awesome-webpack'>;
}
declare module 'font-awesome-webpack/index.loader.js' {
  declare module.exports: $Exports<'font-awesome-webpack/index.loader'>;
}
