// flow-typed signature: 7bda28d0a7ebf123928a5766df17452a
// flow-typed version: <<STUB>>/graphql-client_v^1.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'graphql-client/index' {
  declare module.exports: $Exports<'graphql-client'>;
}
declare module 'graphql-client/index.js' {
  declare module.exports: $Exports<'graphql-client'>;
}
