// flow-typed signature: a3cd5eb49c2865cd8839d55592c22341
// flow-typed version: <<STUB>>/kafka-node_v^0.3.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kafka-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'kafka-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kafka-node/example/consumer' {
  declare module.exports: any;
}

declare module 'kafka-node/example/high-level-consumer' {
  declare module.exports: any;
}

declare module 'kafka-node/example/high-level-producer' {
  declare module.exports: any;
}

declare module 'kafka-node/example/offset' {
  declare module.exports: any;
}

declare module 'kafka-node/example/producer' {
  declare module.exports: any;
}

declare module 'kafka-node/kafka_consumer_test' {
  declare module.exports: any;
}

declare module 'kafka-node/kafka_producer_test' {
  declare module.exports: any;
}

declare module 'kafka-node/kafka' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/batch/KafkaBuffer' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/client' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/codec/index' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/codec/snappy' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/consumer' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/errors/BrokerNotAvailableError' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/errors/FailedToRebalanceConsumerError' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/errors/FailedToRegisterConsumerError' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/errors/index' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/errors/InvalidConsumerOffsetError' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/errors/TopicsNotExistError' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/highLevelConsumer' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/highLevelProducer' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/offset' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/partitioner' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/producer' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/protocol/index' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/protocol/protocol_struct' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/protocol/protocol' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/wrapper/BrokerReadable' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/wrapper/BrokerTransform' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/wrapper/BrokerWrapper' {
  declare module.exports: any;
}

declare module 'kafka-node/lib/zookeeper' {
  declare module.exports: any;
}

declare module 'kafka-node/test/manual.gracefulexit' {
  declare module.exports: any;
}

declare module 'kafka-node/test/test.consumer' {
  declare module.exports: any;
}

declare module 'kafka-node/test/test.offset' {
  declare module.exports: any;
}

declare module 'kafka-node/test/test.partitioner' {
  declare module.exports: any;
}

declare module 'kafka-node/test/test.producer' {
  declare module.exports: any;
}

declare module 'kafka-node/test/test.producerBatch' {
  declare module.exports: any;
}

declare module 'kafka-node/test/test.zookeeper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kafka-node/example/consumer.js' {
  declare module.exports: $Exports<'kafka-node/example/consumer'>;
}
declare module 'kafka-node/example/high-level-consumer.js' {
  declare module.exports: $Exports<'kafka-node/example/high-level-consumer'>;
}
declare module 'kafka-node/example/high-level-producer.js' {
  declare module.exports: $Exports<'kafka-node/example/high-level-producer'>;
}
declare module 'kafka-node/example/offset.js' {
  declare module.exports: $Exports<'kafka-node/example/offset'>;
}
declare module 'kafka-node/example/producer.js' {
  declare module.exports: $Exports<'kafka-node/example/producer'>;
}
declare module 'kafka-node/kafka_consumer_test.js' {
  declare module.exports: $Exports<'kafka-node/kafka_consumer_test'>;
}
declare module 'kafka-node/kafka_producer_test.js' {
  declare module.exports: $Exports<'kafka-node/kafka_producer_test'>;
}
declare module 'kafka-node/kafka.js' {
  declare module.exports: $Exports<'kafka-node/kafka'>;
}
declare module 'kafka-node/lib/batch/KafkaBuffer.js' {
  declare module.exports: $Exports<'kafka-node/lib/batch/KafkaBuffer'>;
}
declare module 'kafka-node/lib/client.js' {
  declare module.exports: $Exports<'kafka-node/lib/client'>;
}
declare module 'kafka-node/lib/codec/index.js' {
  declare module.exports: $Exports<'kafka-node/lib/codec/index'>;
}
declare module 'kafka-node/lib/codec/snappy.js' {
  declare module.exports: $Exports<'kafka-node/lib/codec/snappy'>;
}
declare module 'kafka-node/lib/consumer.js' {
  declare module.exports: $Exports<'kafka-node/lib/consumer'>;
}
declare module 'kafka-node/lib/errors/BrokerNotAvailableError.js' {
  declare module.exports: $Exports<'kafka-node/lib/errors/BrokerNotAvailableError'>;
}
declare module 'kafka-node/lib/errors/FailedToRebalanceConsumerError.js' {
  declare module.exports: $Exports<'kafka-node/lib/errors/FailedToRebalanceConsumerError'>;
}
declare module 'kafka-node/lib/errors/FailedToRegisterConsumerError.js' {
  declare module.exports: $Exports<'kafka-node/lib/errors/FailedToRegisterConsumerError'>;
}
declare module 'kafka-node/lib/errors/index.js' {
  declare module.exports: $Exports<'kafka-node/lib/errors/index'>;
}
declare module 'kafka-node/lib/errors/InvalidConsumerOffsetError.js' {
  declare module.exports: $Exports<'kafka-node/lib/errors/InvalidConsumerOffsetError'>;
}
declare module 'kafka-node/lib/errors/TopicsNotExistError.js' {
  declare module.exports: $Exports<'kafka-node/lib/errors/TopicsNotExistError'>;
}
declare module 'kafka-node/lib/highLevelConsumer.js' {
  declare module.exports: $Exports<'kafka-node/lib/highLevelConsumer'>;
}
declare module 'kafka-node/lib/highLevelProducer.js' {
  declare module.exports: $Exports<'kafka-node/lib/highLevelProducer'>;
}
declare module 'kafka-node/lib/offset.js' {
  declare module.exports: $Exports<'kafka-node/lib/offset'>;
}
declare module 'kafka-node/lib/partitioner.js' {
  declare module.exports: $Exports<'kafka-node/lib/partitioner'>;
}
declare module 'kafka-node/lib/producer.js' {
  declare module.exports: $Exports<'kafka-node/lib/producer'>;
}
declare module 'kafka-node/lib/protocol/index.js' {
  declare module.exports: $Exports<'kafka-node/lib/protocol/index'>;
}
declare module 'kafka-node/lib/protocol/protocol_struct.js' {
  declare module.exports: $Exports<'kafka-node/lib/protocol/protocol_struct'>;
}
declare module 'kafka-node/lib/protocol/protocol.js' {
  declare module.exports: $Exports<'kafka-node/lib/protocol/protocol'>;
}
declare module 'kafka-node/lib/wrapper/BrokerReadable.js' {
  declare module.exports: $Exports<'kafka-node/lib/wrapper/BrokerReadable'>;
}
declare module 'kafka-node/lib/wrapper/BrokerTransform.js' {
  declare module.exports: $Exports<'kafka-node/lib/wrapper/BrokerTransform'>;
}
declare module 'kafka-node/lib/wrapper/BrokerWrapper.js' {
  declare module.exports: $Exports<'kafka-node/lib/wrapper/BrokerWrapper'>;
}
declare module 'kafka-node/lib/zookeeper.js' {
  declare module.exports: $Exports<'kafka-node/lib/zookeeper'>;
}
declare module 'kafka-node/test/manual.gracefulexit.js' {
  declare module.exports: $Exports<'kafka-node/test/manual.gracefulexit'>;
}
declare module 'kafka-node/test/test.consumer.js' {
  declare module.exports: $Exports<'kafka-node/test/test.consumer'>;
}
declare module 'kafka-node/test/test.offset.js' {
  declare module.exports: $Exports<'kafka-node/test/test.offset'>;
}
declare module 'kafka-node/test/test.partitioner.js' {
  declare module.exports: $Exports<'kafka-node/test/test.partitioner'>;
}
declare module 'kafka-node/test/test.producer.js' {
  declare module.exports: $Exports<'kafka-node/test/test.producer'>;
}
declare module 'kafka-node/test/test.producerBatch.js' {
  declare module.exports: $Exports<'kafka-node/test/test.producerBatch'>;
}
declare module 'kafka-node/test/test.zookeeper.js' {
  declare module.exports: $Exports<'kafka-node/test/test.zookeeper'>;
}
