// flow-typed signature: 25926e60283704b0ce039efa77fbb734
// flow-typed version: <<STUB>>/passport-oauth2_v^1.3.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-oauth2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-oauth2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-oauth2/lib/errors/authorizationerror' {
  declare module.exports: any;
}

declare module 'passport-oauth2/lib/errors/internaloautherror' {
  declare module.exports: any;
}

declare module 'passport-oauth2/lib/errors/tokenerror' {
  declare module.exports: any;
}

declare module 'passport-oauth2/lib/index' {
  declare module.exports: any;
}

declare module 'passport-oauth2/lib/state/null' {
  declare module.exports: any;
}

declare module 'passport-oauth2/lib/state/session' {
  declare module.exports: any;
}

declare module 'passport-oauth2/lib/strategy' {
  declare module.exports: any;
}

declare module 'passport-oauth2/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-oauth2/lib/errors/authorizationerror.js' {
  declare module.exports: $Exports<'passport-oauth2/lib/errors/authorizationerror'>;
}
declare module 'passport-oauth2/lib/errors/internaloautherror.js' {
  declare module.exports: $Exports<'passport-oauth2/lib/errors/internaloautherror'>;
}
declare module 'passport-oauth2/lib/errors/tokenerror.js' {
  declare module.exports: $Exports<'passport-oauth2/lib/errors/tokenerror'>;
}
declare module 'passport-oauth2/lib/index.js' {
  declare module.exports: $Exports<'passport-oauth2/lib/index'>;
}
declare module 'passport-oauth2/lib/state/null.js' {
  declare module.exports: $Exports<'passport-oauth2/lib/state/null'>;
}
declare module 'passport-oauth2/lib/state/session.js' {
  declare module.exports: $Exports<'passport-oauth2/lib/state/session'>;
}
declare module 'passport-oauth2/lib/strategy.js' {
  declare module.exports: $Exports<'passport-oauth2/lib/strategy'>;
}
declare module 'passport-oauth2/lib/utils.js' {
  declare module.exports: $Exports<'passport-oauth2/lib/utils'>;
}
