// flow-typed signature: 4ba88405fa9fc72e8c3fed224b8c22b4
// flow-typed version: <<STUB>>/piping_v^0.3.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'piping'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'piping' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'piping/lib/launcher' {
  declare module.exports: any;
}

declare module 'piping/lib/piping' {
  declare module.exports: any;
}

declare module 'piping/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'piping/lib/launcher.js' {
  declare module.exports: $Exports<'piping/lib/launcher'>;
}
declare module 'piping/lib/piping.js' {
  declare module.exports: $Exports<'piping/lib/piping'>;
}
declare module 'piping/test.js' {
  declare module.exports: $Exports<'piping/test'>;
}
