// flow-typed signature: a1a815e615b13a4727292091a970e9f5
// flow-typed version: <<STUB>>/react-addons-test-utils_v^0.14.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-addons-test-utils/index' {
  declare module.exports: $Exports<'react-addons-test-utils'>;
}
declare module 'react-addons-test-utils/index.js' {
  declare module.exports: $Exports<'react-addons-test-utils'>;
}
