// flow-typed signature: 35e35aa89beb82944174e634379e1f69
// flow-typed version: <<STUB>>/react-inline-css_v^2.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-inline-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-inline-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-inline-css/src/react-inline-css' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-inline-css/src/react-inline-css.js' {
  declare module.exports: $Exports<'react-inline-css/src/react-inline-css'>;
}
