// flow-typed signature: 9559e174cf33fe26282ac299ad5fd7fa
// flow-typed version: <<STUB>>/react-helmet_v^2.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-helmet/config/clean' {
  declare module.exports: any;
}

declare module 'react-helmet/config/eslint' {
  declare module.exports: any;
}

declare module 'react-helmet/gulpfile' {
  declare module.exports: any;
}

declare module 'react-helmet/karma.config' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/Helmet' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/HelmetConstants' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/index' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/PlainComponent' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/test/HelmetTest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-helmet/config/clean.js' {
  declare module.exports: $Exports<'react-helmet/config/clean'>;
}
declare module 'react-helmet/config/eslint.js' {
  declare module.exports: $Exports<'react-helmet/config/eslint'>;
}
declare module 'react-helmet/gulpfile.js' {
  declare module.exports: $Exports<'react-helmet/gulpfile'>;
}
declare module 'react-helmet/karma.config.js' {
  declare module.exports: $Exports<'react-helmet/karma.config'>;
}
declare module 'react-helmet/lib/Helmet.js' {
  declare module.exports: $Exports<'react-helmet/lib/Helmet'>;
}
declare module 'react-helmet/lib/HelmetConstants.js' {
  declare module.exports: $Exports<'react-helmet/lib/HelmetConstants'>;
}
declare module 'react-helmet/lib/index.js' {
  declare module.exports: $Exports<'react-helmet/lib/index'>;
}
declare module 'react-helmet/lib/PlainComponent.js' {
  declare module.exports: $Exports<'react-helmet/lib/PlainComponent'>;
}
declare module 'react-helmet/lib/test/HelmetTest.js' {
  declare module.exports: $Exports<'react-helmet/lib/test/HelmetTest'>;
}
