// flow-typed signature: c463a2b9de2e8565f73912c2e50a0ee4
// flow-typed version: <<STUB>>/redux-form-validation_v0.0.6/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-form-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-form-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-form-validation/dist/redux-form-validation' {
  declare module.exports: any;
}

declare module 'redux-form-validation/dist/redux-form-validation.min' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/creditcard.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/digits.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/email.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/equalTo.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/matchField.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/max.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/maxLength.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/min.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/minLength.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/oneOf.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/pattern.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/promise.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/required.spec' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/__tests__/setup' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/basic-validations' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/form-messages/index' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/index' {
  declare module.exports: any;
}

declare module 'redux-form-validation/lib/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-form-validation/dist/redux-form-validation.js' {
  declare module.exports: $Exports<'redux-form-validation/dist/redux-form-validation'>;
}
declare module 'redux-form-validation/dist/redux-form-validation.min.js' {
  declare module.exports: $Exports<'redux-form-validation/dist/redux-form-validation.min'>;
}
declare module 'redux-form-validation/lib/__tests__/creditcard.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/creditcard.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/digits.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/digits.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/email.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/email.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/equalTo.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/equalTo.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/matchField.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/matchField.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/max.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/max.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/maxLength.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/maxLength.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/min.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/min.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/minLength.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/minLength.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/oneOf.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/oneOf.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/pattern.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/pattern.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/promise.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/promise.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/required.spec.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/required.spec'>;
}
declare module 'redux-form-validation/lib/__tests__/setup.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/__tests__/setup'>;
}
declare module 'redux-form-validation/lib/basic-validations.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/basic-validations'>;
}
declare module 'redux-form-validation/lib/form-messages/index.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/form-messages/index'>;
}
declare module 'redux-form-validation/lib/index.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/index'>;
}
declare module 'redux-form-validation/lib/validation.js' {
  declare module.exports: $Exports<'redux-form-validation/lib/validation'>;
}
