// flow-typed signature: e3c2da9f94ab4c8296d04455f4a9d594
// flow-typed version: <<STUB>>/redux-promise_v^0.5.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-promise/lib/__tests__/init' {
  declare module.exports: any;
}

declare module 'redux-promise/lib/__tests__/promiseMiddleware-test' {
  declare module.exports: any;
}

declare module 'redux-promise/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-promise/lib/__tests__/init.js' {
  declare module.exports: $Exports<'redux-promise/lib/__tests__/init'>;
}
declare module 'redux-promise/lib/__tests__/promiseMiddleware-test.js' {
  declare module.exports: $Exports<'redux-promise/lib/__tests__/promiseMiddleware-test'>;
}
declare module 'redux-promise/lib/index.js' {
  declare module.exports: $Exports<'redux-promise/lib/index'>;
}
