// flow-typed signature: 321d9d04a6360fc1a0b2079465c3c3cd
// flow-typed version: <<STUB>>/redux-localstorage_v^0.4.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-localstorage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-localstorage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-localstorage/lib/createSlicer' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/getSubset' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/persistState' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/util/mergeState' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/util/typeOf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-localstorage/lib/createSlicer.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/createSlicer'>;
}
declare module 'redux-localstorage/lib/getSubset.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/getSubset'>;
}
declare module 'redux-localstorage/lib/persistState.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/persistState'>;
}
declare module 'redux-localstorage/lib/util/mergeState.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/util/mergeState'>;
}
declare module 'redux-localstorage/lib/util/typeOf.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/util/typeOf'>;
}
