// flow-typed signature: bd070f83952ec0659254196c19a9e10e
// flow-typed version: <<STUB>>/scroll-behavior_v^0.3.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scroll-behavior'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scroll-behavior' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scroll-behavior/es6/index' {
  declare module.exports: any;
}

declare module 'scroll-behavior/es6/useScrollToTop' {
  declare module.exports: any;
}

declare module 'scroll-behavior/es6/useSimpleScroll' {
  declare module.exports: any;
}

declare module 'scroll-behavior/es6/useStandardScroll' {
  declare module.exports: any;
}

declare module 'scroll-behavior/es6/utils/createUseScroll' {
  declare module.exports: any;
}

declare module 'scroll-behavior/es6/utils/setScrollRestoration' {
  declare module.exports: any;
}

declare module 'scroll-behavior/lib/index' {
  declare module.exports: any;
}

declare module 'scroll-behavior/lib/useScrollToTop' {
  declare module.exports: any;
}

declare module 'scroll-behavior/lib/useSimpleScroll' {
  declare module.exports: any;
}

declare module 'scroll-behavior/lib/useStandardScroll' {
  declare module.exports: any;
}

declare module 'scroll-behavior/lib/utils/createUseScroll' {
  declare module.exports: any;
}

declare module 'scroll-behavior/lib/utils/setScrollRestoration' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scroll-behavior/es6/index.js' {
  declare module.exports: $Exports<'scroll-behavior/es6/index'>;
}
declare module 'scroll-behavior/es6/useScrollToTop.js' {
  declare module.exports: $Exports<'scroll-behavior/es6/useScrollToTop'>;
}
declare module 'scroll-behavior/es6/useSimpleScroll.js' {
  declare module.exports: $Exports<'scroll-behavior/es6/useSimpleScroll'>;
}
declare module 'scroll-behavior/es6/useStandardScroll.js' {
  declare module.exports: $Exports<'scroll-behavior/es6/useStandardScroll'>;
}
declare module 'scroll-behavior/es6/utils/createUseScroll.js' {
  declare module.exports: $Exports<'scroll-behavior/es6/utils/createUseScroll'>;
}
declare module 'scroll-behavior/es6/utils/setScrollRestoration.js' {
  declare module.exports: $Exports<'scroll-behavior/es6/utils/setScrollRestoration'>;
}
declare module 'scroll-behavior/lib/index.js' {
  declare module.exports: $Exports<'scroll-behavior/lib/index'>;
}
declare module 'scroll-behavior/lib/useScrollToTop.js' {
  declare module.exports: $Exports<'scroll-behavior/lib/useScrollToTop'>;
}
declare module 'scroll-behavior/lib/useSimpleScroll.js' {
  declare module.exports: $Exports<'scroll-behavior/lib/useSimpleScroll'>;
}
declare module 'scroll-behavior/lib/useStandardScroll.js' {
  declare module.exports: $Exports<'scroll-behavior/lib/useStandardScroll'>;
}
declare module 'scroll-behavior/lib/utils/createUseScroll.js' {
  declare module.exports: $Exports<'scroll-behavior/lib/utils/createUseScroll'>;
}
declare module 'scroll-behavior/lib/utils/setScrollRestoration.js' {
  declare module.exports: $Exports<'scroll-behavior/lib/utils/setScrollRestoration'>;
}
