// flow-typed signature: ba9247a9ff7b6f1b2dbcb3d37db1d890
// flow-typed version: <<STUB>>/storybook-addon-material-ui_v^0.7.4/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-material-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-material-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-material-ui/dist/components/ThemePanel' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/components/ThemePropBlock' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/components/ThemePropItem' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/components/ThemeSideBar' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/containers/MuiTheme' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/containers/PanelContainer' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/material-desktop/SclAvatar' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/material-desktop/SclToggle' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/material-desktop/SvgButton' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/material-desktop/SvgIcon' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/muiTheme' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/dist/Utils/index' {
  declare module.exports: any;
}

declare module 'storybook-addon-material-ui/mochacfg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-material-ui/dist/components/ThemePanel.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/components/ThemePanel'>;
}
declare module 'storybook-addon-material-ui/dist/components/ThemePropBlock.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/components/ThemePropBlock'>;
}
declare module 'storybook-addon-material-ui/dist/components/ThemePropItem.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/components/ThemePropItem'>;
}
declare module 'storybook-addon-material-ui/dist/components/ThemeSideBar.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/components/ThemeSideBar'>;
}
declare module 'storybook-addon-material-ui/dist/containers/MuiTheme.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/containers/MuiTheme'>;
}
declare module 'storybook-addon-material-ui/dist/containers/PanelContainer.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/containers/PanelContainer'>;
}
declare module 'storybook-addon-material-ui/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/index'>;
}
declare module 'storybook-addon-material-ui/dist/material-desktop/SclAvatar.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/material-desktop/SclAvatar'>;
}
declare module 'storybook-addon-material-ui/dist/material-desktop/SclToggle.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/material-desktop/SclToggle'>;
}
declare module 'storybook-addon-material-ui/dist/material-desktop/SvgButton.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/material-desktop/SvgButton'>;
}
declare module 'storybook-addon-material-ui/dist/material-desktop/SvgIcon.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/material-desktop/SvgIcon'>;
}
declare module 'storybook-addon-material-ui/dist/muiTheme.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/muiTheme'>;
}
declare module 'storybook-addon-material-ui/dist/register.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/register'>;
}
declare module 'storybook-addon-material-ui/dist/Utils/index.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/dist/Utils/index'>;
}
declare module 'storybook-addon-material-ui/mochacfg.js' {
  declare module.exports: $Exports<'storybook-addon-material-ui/mochacfg'>;
}
